#开发环境配置文件
server:
  port: 8080

#配置数据库
spring:
  datasource:
    url: jdbc:mysql://host:3306/youth?useSSL=false&serverTimezone=UTC
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  #配置redis
  data:
    redis:
      host:
      password:
      port: 6379
      timeout: 30000
  #开启热部署
  #说明：新版本idea配置热部署，
  #Compiler->build project automatically 和
  #Advanced Settings->Allow auto-make to start even if development application is currently running 都要勾选
  devtools:
    restart:
      enabled: true
      ###设置重启的目录
      additional-paths: src/**
      ###解决项目自动重新编译后接口报404的问题
      poll-interval: 3000
      quiet-period: 1000
  #设置项目名称
  application:
    name: youth

#mybatis-plus配置
mybatis-plus:
  configuration:
    logImpl: org.apache.ibatis.logging.stdout.StdOutImpl

#jwt配置
jwt:
  header: Authorization
  #签名32位字符串
  secret: woshiwudidewwwqwerdsfkshwyustwhs
  #过期时间
  expiration:
    token:
      #单位毫秒
      access: 1800000
      refresh: 18000000

#swagger配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'youth'
      paths-to-match: '/**'
      #生成文档所需的扫包路径，一般为启动类目录
      packages-to-scan: com.youth


#knife4j配置
knife4j:
  #是否启用增强设置
  enable: true
  #开启生产环境屏蔽
  production: false
  setting:
    language: zh_cn
    enable-version: true
    enable-swagger-models: true
    swagger-model-name: youth模块